trigger:
  - production

variables:
  - name: major
    value: 0
  - name: minor
    value: 0
  - name: patch
    value: 1

name: $(major).$(minor).$(patch)-$(Rev:r)

stages:
  - stage: deploy
    displayName: Deploy
    condition:
      not(eq(variables['build.reason'], 'PullRequest'))
    jobs:
      - job: deployToStaging
        displayName: Deploy to Production
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: Docker@2
            displayName: Push Docker Image
            inputs:
              command: buildAndPush
              containerRegistry: SteeltoeContainerRegistry
              repository: initializr-cli
              tags: |
                $(Build.BuildId)
                latest
          - task: KubernetesManifest@0
            displayName: Deploy to Production Cluster
            inputs:
              action: deploy
              kubernetesServiceConnection: SteeltoeProductionAKS
              manifests: deploy/kubernetes/manifest.yaml
              containers: steeltoe.azurecr.io/initializr-cli:$(Build.BuildId)
              namespace: initializr
