---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: initializr-cli
  namespace: initializr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: initializr-cli
  template:
    metadata:
      labels:
        app: initializr-cli
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: initializr-cli
        image: steeltoe.azurecr.io/initializr-cli
